### ISSUE TITLE
Won't start on Raspberry PI 4

### ISSUE THREAD

**Issue by matonb** [mongodb-js/compass#2230]
I'm probably doing something wrong but I can't get compass to start on a Raspberry Pi4 (ubuntu server 21.04 64)

What I've tried (running from master branch):

```
npm start

> start
> lerna run start --stream --scope mongodb-compass

sh: 1: lerna: not found
```

```
npm i lerna
...
npm run start

> start
> lerna run start --stream --scope mongodb-compass

lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "mongodb-compass"
lerna info filter [ 'mongodb-compass' ]
lerna info Executing command in 1 package: "npm run start"
mongodb-compass: > mongodb-compass@0.0.0-dev.0 prestart
mongodb-compass: > rm -rf .compiled-sources
mongodb-compass: > mongodb-compass@0.0.0-dev.0 start
mongodb-compass: > hadron-build develop
mongodb-compass: sh: 1: hadron-build: not found
lerna ERR! npm run start exited 127 in 'mongodb-compass'
```

```
npm i hadron-build
...
npm run start

> start
> lerna run start --stream --scope mongodb-compass

lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "mongodb-compass"
lerna info filter [ 'mongodb-compass' ]
lerna info Executing command in 1 package: "npm run start"
mongodb-compass: > mongodb-compass@0.0.0-dev.0 prestart
mongodb-compass: > rm -rf .compiled-sources
mongodb-compass: > mongodb-compass@0.0.0-dev.0 start
mongodb-compass: > hadron-build develop
mongodb-compass: ✖  Error: [LessError] {
mongodb-compass:   message: undefined,
mongodb-compass:   stack: undefined,
mongodb-compass:   type: 'Syntax',
mongodb-compass:   filename: '/home/matonb/gitlab/node-course/compass/packages/compass/src/app/styles/bootstrap.less',
mongodb-compass:   index: 29,
mongodb-compass:   line: 2,
mongodb-compass:   column: 0,
mongodb-compass:   callLine: NaN,
mongodb-compass:   callExtract: undefined,
mongodb-compass:   extract: [
mongodb-compass:     '// Core variables and mixins',
mongodb-compass:     '@import "../../../node_modules/bootstrap/less/variables.less";',
mongodb-compass:     '@import "../../../node_modules/bootstrap/less/mixins.less";'
mongodb-compass:   ]
mongodb-compass: }
mongodb-compass: Unhandled rejection TypeError: Cannot read property 'split' of undefined
mongodb-compass:     at CLI.error (/home/matonb/gitlab/node-course/compass/node_modules/mongodb-js-cli/lib/index.js:101:15)
mongodb-compass:     at CLI.abortIfError (/home/matonb/gitlab/node-course/compass/node_modules/mongodb-js-cli/lib/index.js:114:8)
mongodb-compass:     at /home/matonb/gitlab/node-course/compass/node_modules/hadron-build/commands/develop.js:52:25
mongodb-compass:     at tryCatcher (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/util.js:16:23)
mongodb-compass:     at Promise._settlePromiseFromHandler (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/promise.js:547:31)
mongodb-compass:     at Promise._settlePromise (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/promise.js:604:18)
mongodb-compass:     at Promise._settlePromise0 (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/promise.js:649:10)
mongodb-compass:     at Promise._settlePromises (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/promise.js:725:18)
mongodb-compass:     at _drainQueueStep (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/async.js:93:12)
mongodb-compass:     at _drainQueue (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/async.js:86:9)
mongodb-compass:     at Async._drainQueues (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/async.js:102:5)
mongodb-compass:     at Immediate.Async.drainQueues [as _onImmediate] (/home/matonb/gitlab/node-course/compass/node_modules/bluebird/js/release/async.js:15:14)
mongodb-compass:     at processImmediate (internal/timers.js:461:21)
lerna success run Ran npm script 'start' in 1 package in 8.7s:
lerna success - mongodb-compass
```

Any suggestions appreciated

**Comment by Anemy** [comment]
Hi @matonb - nice to see you're trying it out. For the first error about `lerna: not found`
Can you try `npm install -g lerna` ?
You've caught this project at an interesting time - we are actually currently in the process of updating how Compass' development works, so this should be a bit easier in about a week.

Which node version are you using?

**Comment by matonb** [comment]
Hi @Anemy ,

  I fixed the lerna one, code block two above with `npm i lerna`
  As for node version, I think it was major 12 not sure on the minor.
  
  I rebuilt the machine it's now on 16.3.0, but not tried compass again

**Comment by gribnoysup** [comment]
Hey @matonb, we are currently in the process of migrating the whole thing to the monorepo and the docs are not up to date with the current process, the migration is not finished yet, so it might be awhile before we get to the docs, sorry for that.

If you just want to run compass locally from the repository while we are migrating the repo, the easiest way of doing this would be to skip running anything from the root of the repo and just do everything mentioned in the docs from the `packages/compass` folder. You also need to be on node 12 to be able to build and run Compass locally

So something like that from the root of the repo:

```
# If you are using nvm to manage node versions
nvm use 12
cd packages/compass
npm install
npm run start
```

**Comment by matonb** [comment]
Hi @gribnoysup, thanks for the info I'll give it a go when I get chance.

**Comment by Anemy** [comment]
@matonb Did it work out? Going to close this ticket for now, feel free to re-open.
We've updated the documentation on the main page now that the restructuring has completed, so it's a good place to find out how to get up and running now.
